export * from './domain/entities/AnalysisReportEntity';
export * from './domain/entities/DiagnosticEntity';
export * from './domain/entities/InferenceRuleEntity';
export * from './domain/entities/LanguagePackageEntity';
export * from './domain/entities/ValidationResultEntity';
export * from './domain/errors/DomainErrors';
export * from './domain/services/EducationalFeedbackService';
export * from './domain/services/LogicValidationService';
export * from './domain/services/PatternRecognitionService';